
server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 11.101.4.244
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    #    virtual-host: JCcccHost
#   设置发布确认方式
    publisher-returns: true
    publisher-confirm-type: correlated

